### ISSUE TITLE
Plugin incompatible with Node.js `exports` package.json field #104

### ISSUE THREAD

**Issue by ConProgramming** [rixo/rollup-plugin-svelte-hot#8] opened 2020-08-27 15:10 UTC
This issue was fixed in main rollup-plugin-svelte https://github.com/sveltejs/rollup-plugin-svelte/issues/104

**Comment by rixo** [comment] 2020-08-27 23:48
Thanks for the notice.

I'm a bit time compressed so I made a quick merge of the official plugin and released as `rollup-plugin-svelte-hot@next` (0.11.0-0) for now.

Can you try it and see if the problem is solved? ... and maybe if everything else looks in order ^^

**Comment by rixo** [comment] 2020-10-21 21:41
Well, I guess it is...

**Closed as completed by rixo** 2020-10-21 21:41 UTC
