### ISSUE TITLE
TypeError: Cannot read property '__esModule' of undefined

### ISSUE THREAD

**Issue by frederikhors** [rixo/rollup-plugin-svelte-hot#9] opened 2020-09-22 16:49 UTC
I'm trying to import `gql` like this:

`import gql from 'graphql-tag'`.

It works great with default `sveltejs/template` rollup flow, but here I have this error:

`TypeError: Cannot read property '__esModule' of undefined`.

If I remove that line it works.

Can I ask you why?

**Comment by frederikhors** [comment] 2020-09-22 17:03
I'm using `npm run dev:rollup` here.

**Comment by frederikhors** [comment] 2020-09-22 18:22
This is because of https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#v1510.

If I revert back to 5.0.0 everything works fine.

**Comment by rixo** [comment] 2020-09-22 22:26
Thanks. It's a regression in `@rollup/plugin-commonjs@15.1.0` apparently. I've provided a minimal repro there, ~~they'll probably reopen the issue and / or fix it~~ they will have reopened it before I've even finished commenting here. :sweat_smile: 

I'm closing here because I don't think there's anything that can be done on my side. Maybe I'll pin the version of the Rollup plugin pending a fix if the issue pops again for other people / libs. Feel free to reopen or ping me in the other issue if more debugging of my template is needed.

**Closed as completed by rixo** 2020-09-22 22:26 UTC
